name: 'Hashnode Auto Publisher'
description: 'Automatically publish articles to Hashnode from your repository'
author: 'Gokul Nathan B'
branding:
  icon: 'edit-3'
  color: 'blue'

inputs:
  hashnode-pat:
    description: 'Hashnode Personal Access Token'
    required: true
  hashnode-publication-id:
    description: 'Hashnode Publication ID'
    required: true
  hashnode-publication-host:
    description: 'Hashnode Publication Host'
    required: true
  github-token:
    description: 'GitHub Token with repository variables write permission'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  content-path:
    description: 'Path to the content/markdown files in user repo'
    required: false
    default: 'content'
  saved-post-id:
    description: 'Previously saved Hashnode post ID'
    required: false
    default: ''
  saved-post-slug:
    description: 'Previously saved Hashnode post slug'
    required: false
    default: ''
  saved-post-title:
    description: 'Previously saved Hashnode post title'
    required: false
    default: ''
  saved-post-url:
    description: 'Previously saved Hashnode post URL'
    required: false
    default: ''
  saved-post-published-at:
    description: 'Previously saved Hashnode post published date'
    required: false
    default: ''
  saved-post-updated-at:
    description: 'Previously saved Hashnode post updated date'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout action repository
      uses: actions/checkout@v4
      with:
        repository: gokulnathan66/article-automation
        path: action-repo
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    
    - name: Install action dependencies
      run: |
        cd action-repo
        if [ -f package.json ]; then
          npm install
          echo "✅ Installed action dependencies"
        else
          echo "No package.json found in action repo"
        fi
      shell: bash
      
    - name: Process Hashnode article
      run: |
        # Load saved variables from inputs
        if [ -n "${{ inputs.saved-post-id }}" ]; then
          export HASHNODE_SAVED_POST_ID="${{ inputs.saved-post-id }}"
          export HASHNODE_SAVED_POST_SLUG="${{ inputs.saved-post-slug }}"
          export HASHNODE_SAVED_POST_TITLE="${{ inputs.saved-post-title }}"
          export HASHNODE_SAVED_POST_URL="${{ inputs.saved-post-url }}"
          export HASHNODE_SAVED_POST_PUBLISHED_AT="${{ inputs.saved-post-published-at }}"
          export HASHNODE_SAVED_POST_UPDATED_AT="${{ inputs.saved-post-updated-at }}"
          echo "✅ Previous Hashnode post data loaded from inputs"
        else
          echo "ℹ️ No previous Hashnode post data found"
        fi
        
        # Set content path for the script
        export USER_CONTENT_PATH="${{ inputs.content-path }}"
        export USER_REPO_PATH="$GITHUB_WORKSPACE"
        
        # Debug: Show environment
        echo "🔍 Debug Info:"
        echo "- USER_REPO_PATH: $USER_REPO_PATH"
        echo "- USER_CONTENT_PATH: $USER_CONTENT_PATH"
        echo "- Current directory: $(pwd)"
        echo "- User repo contents:"
        ls -la "$USER_REPO_PATH" || echo "User repo path not found"
        echo "- Content directory:"
        ls -la "$USER_REPO_PATH/$USER_CONTENT_PATH" 2>/dev/null || echo "Content directory not found"
        
        # Run script from action repository
        echo "🔄 Processing Hashnode article..."
        cd action-repo
        
        # Check if script exists
        if [ ! -f "hashnode-publish/scripts/hashnode.js" ]; then
          echo "❌ Error: hashnode.js script not found!"
          echo "Available files in action-repo:"
          find . -name "*.js" -type f 2>/dev/null || echo "No JS files found"
          exit 1
        fi
        
        # Run script with error capture
        echo "📝 Running Node.js script..."
        if node hashnode-publish/scripts/hashnode.js > ../post_output.json 2>../script_error.log; then
          echo "✅ Script executed successfully"
        else
          SCRIPT_EXIT_CODE=$?
          echo "❌ Script execution failed with exit code: $SCRIPT_EXIT_CODE"
          echo "Error output:"
          cat ../script_error.log 2>/dev/null || echo "No error log available"
          echo "Script stdout:"
          cat ../post_output.json 2>/dev/null || echo "No output file generated"
          exit $SCRIPT_EXIT_CODE
        fi
        
        cd ..
        
        # Validate and process JSON
        if jq empty post_output.json 2>/dev/null; then
          echo "✅ Hashnode article processed successfully"
          
          # Extract data silently
          POST_ID=$(jq -r '.id' post_output.json)
          POST_SLUG=$(jq -r '.slug' post_output.json)
          POST_TITLE=$(jq -r '.title' post_output.json)
          POST_URL=$(jq -r '.url' post_output.json)
          POST_PUBLISHED_AT=$(jq -r '.published_at' post_output.json)
          POST_UPDATED_AT=$(jq -r '.updated_at' post_output.json)
          
          # Save to repository variables silently
          echo "💾 Updating Hashnode repository variables..."
          
          VARS=(
            "HASHNODE_SAVED_POST_ID:$POST_ID"
            "HASHNODE_SAVED_POST_SLUG:$POST_SLUG"
            "HASHNODE_SAVED_POST_TITLE:$POST_TITLE"
            "HASHNODE_SAVED_POST_URL:$POST_URL"
            "HASHNODE_SAVED_POST_PUBLISHED_AT:$POST_PUBLISHED_AT"
            "HASHNODE_SAVED_POST_UPDATED_AT:$POST_UPDATED_AT"
          )
          
          for var_pair in "${VARS[@]}"; do
            VAR_NAME="${var_pair%%:*}"
            VAR_VALUE="${var_pair#*:}"
            
            # Update or create variable silently
            gh api --method PATCH "/repos/${{ github.repository }}/actions/variables/$VAR_NAME" \
              -f name="$VAR_NAME" -f value="$VAR_VALUE" >/dev/null 2>&1 || \
            gh api --method POST "/repos/${{ github.repository }}/actions/variables" \
              -f name="$VAR_NAME" -f value="$VAR_VALUE" >/dev/null 2>&1
          done
          
          echo "✅ Hashnode repository variables updated"
          echo "📢 Article processing completed on Hashnode"
          echo "🔗 Check your Hashnode dashboard for the published/updated article"
          
          # Clean up
          rm -f post_output.json script_error.log
          
        else
          echo "❌ Error: Invalid JSON output from Hashnode script"
          echo "Script output (for debugging):"
          cat post_output.json 2>/dev/null || echo "No output file"
          echo "Error log:"
          cat script_error.log 2>/dev/null || echo "No error log"
          exit 1
        fi
      shell: bash
      env:
        HASHNODE_PAT: ${{ inputs.hashnode-pat }}
        HASHNODE_PUBLICATION_ID: ${{ inputs.hashnode-publication-id }}
        HASHNODE_PUBLICATION_HOST: ${{ inputs.hashnode-publication-host }}
        GITHUB_USERNAME: ${{ github.repository_owner }}
        GITHUB_REPO: ${{ github.event.repository.name }}
        GITHUB_BRANCH: ${{ github.ref_name }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
